language: node_js
node_js:
  - "10"
branches:
  only:
  - develop
  - v/^v\d+.\d+.\d+$/

env:
  - REPO=kuroneko

jobs:
  include:
    - stage: "Lint"
      script: npm run lint
    - stage: "Test"
      script: npm run test-headless
    - stage: "Build"
      script: npm run build
      after_success:
        - if [ -n "$TRAVIS_TAG" ]; then
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "rm -rf deploy/$REPO
            mkdir -p deploy/$REPO"
            scp -o StrictHostKeyChecking=no -r dist/* $SSH_USER@$SSH_HOST:deploy/$REPO
          fi
